services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      target: webserver
    environment:
      INFLUXDB_HOST: "influxdb:8086"
      PYROSCOPE_HOST: "http://pyroscope:4040"
    ports:
      - "8080:8080"
    depends_on:
      influxdb:
        condition: service_healthy
    healthcheck:
        test: curl -f http://localhost:8080/ping || exit 1
        interval: 1s
        timeout: 1s
        retries: 30
    memswap_limit: 100M
    deploy:
      resources:
        limits:
          memory: 100M
    restart: on-failure

  loadgen:
    build:
      context: .
      dockerfile: Dockerfile
      target: loadgen
    depends_on:
      webserver:
        condition: service_healthy
    command: "/app/loadgen -c 3 -i 10ms -t http://webserver:8080/create?delay=10s"
    restart: always

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    healthcheck:
      test: curl -f http://localhost:8086/ping || exit 1
      interval: 3s
      timeout: 10s
      retries: 30

  grafana:
    image: grafana/grafana:8.1.7
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning

  pyroscope:
    image: grafana/pyroscope:1.6.1
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "4040:4040"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"