// Code generated by MockGen. DO NOT EDIT.
// Source: user.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(ctx context.Context, name, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(ctx, name, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), ctx, name, email)
}

// MockAnalytics is a mock of Analytics interface.
type MockAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyticsMockRecorder
}

// MockAnalyticsMockRecorder is the mock recorder for MockAnalytics.
type MockAnalyticsMockRecorder struct {
	mock *MockAnalytics
}

// NewMockAnalytics creates a new mock instance.
func NewMockAnalytics(ctrl *gomock.Controller) *MockAnalytics {
	mock := &MockAnalytics{ctrl: ctrl}
	mock.recorder = &MockAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalytics) EXPECT() *MockAnalyticsMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockAnalytics) Send(ctx context.Context, message string, args ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, message}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Send", varargs...)
}

// Send indicates an expected call of Send.
func (mr *MockAnalyticsMockRecorder) Send(ctx, message interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, message}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockAnalytics)(nil).Send), varargs...)
}

// MockbarService is a mock of barService interface.
type MockbarService struct {
	ctrl     *gomock.Controller
	recorder *MockbarServiceMockRecorder
}

// MockbarServiceMockRecorder is the mock recorder for MockbarService.
type MockbarServiceMockRecorder struct {
	mock *MockbarService
}

// NewMockbarService creates a new mock instance.
func NewMockbarService(ctrl *gomock.Controller) *MockbarService {
	mock := &MockbarService{ctrl: ctrl}
	mock.recorder = &MockbarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbarService) EXPECT() *MockbarServiceMockRecorder {
	return m.recorder
}

// GetBarID mocks base method.
func (m *MockbarService) GetBarID(ctx context.Context, id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBarID", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBarID indicates an expected call of GetBarID.
func (mr *MockbarServiceMockRecorder) GetBarID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBarID", reflect.TypeOf((*MockbarService)(nil).GetBarID), ctx, id)
}

// MockbazService is a mock of bazService interface.
type MockbazService struct {
	ctrl     *gomock.Controller
	recorder *MockbazServiceMockRecorder
}

// MockbazServiceMockRecorder is the mock recorder for MockbazService.
type MockbazServiceMockRecorder struct {
	mock *MockbazService
}

// NewMockbazService creates a new mock instance.
func NewMockbazService(ctrl *gomock.Controller) *MockbazService {
	mock := &MockbazService{ctrl: ctrl}
	mock.recorder = &MockbazServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbazService) EXPECT() *MockbazServiceMockRecorder {
	return m.recorder
}

// GetBazID mocks base method.
func (m *MockbazService) GetBazID(ctx context.Context, id int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBazID", ctx, id)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBazID indicates an expected call of GetBazID.
func (mr *MockbazServiceMockRecorder) GetBazID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBazID", reflect.TypeOf((*MockbazService)(nil).GetBazID), ctx, id)
}
